#!/usr/bin/Rscript

#### Title: Numbat for melanoma samples
#### Author: Jana Biermann, PhD

library(numbat)
library(dplyr)
library(Seurat)
'%notin%' <- Negate('%in%')

# Provide sample name as argument
pat<- commandArgs()[6]

# Read in complete cohort
seu_all<-readRDS('data/merged/data_melanoma_merged_v2.rds')

# Sync-in from AWS
print(paste('Processing:', pat))
system(paste0('aws s3 cp s3://XYZ/numbat/',pat,'/',pat,'_allele_counts.tsv.gz data/',pat,'/ --quiet'))

# Get count_mat for pat
seu<-subset(seu_all,orig.ident==pat)
count_mat<-seu@assays$RNA@counts
colnames(count_mat)<-seu$barcode_orig

# Get ref_mat from entire cohort 
# (in melanoma cohort tumor cells are usually recognized as 'melanocytes' in SingleR BPED)
seu_all$annot<-ifelse(is.na(seu_all$celltype_bped_main)==T, 'unknown',seu_all$celltype_bped_main)
notum<-subset(seu_all,annot %notin% c('Melanocytes','unknown'))
ref_mat<-notum@assays$RNA@counts
colnames(ref_mat)<-notum$barcode_orig

# count_mat is a gene x cell raw count matrices
# cell_annot is a dataframe with columns "cell" and "group"
cell_annot=data.frame(cell=notum$barcode_orig,group=notum$annot)
ref_internal = aggregate_counts(ref_mat, cell_annot)

# allele dataframe generated by pileup_and_phase script
df_allele<-read.delim(paste0('data/',pat,'/',pat,'_allele_counts.tsv.gz'))
df_allele<- subset(df_allele,cell %in% seu$barcode_orig)

rm(list = c('seu','seu_all','notum'))

out = run_numbat(count_mat=count_mat, # gene x cell integer UMI count matrix 
                 lambdas_ref=ref_internal, # reference expression profile, a gene x cell type normalized expression level matrix
                 df_allele=df_allele, # allele dataframe generated by pileup_and_phase script
                 out_dir= paste0('data/',pat),
                 genome = "hg38",
                 ncores = 16,
                 plot = TRUE)

saveRDS(out,paste0('data/',pat,'/',pat,'_numbat_out.rds'))

# Run plotting script
system(paste0('Rscript ~/single_cell_tools/numbat/3_numbat_plots.R ',pat))

# Sync-out to AWS
system(paste0("aws s3 sync data/",pat,"/ s3://XYZ/numbat/",pat,"/ --exclude '*_cnv.rds' --quiet"))
print(paste('Finished:', pat))
